#' The file contains code to analyze the data $DATA for the project
#' $PROJECT.  This script likely contains a large portion of code for
#' generating graphics, plots, and regression diagnostics.  However,
#' it may also contain code for the main analysis for the project.
#'
#' @author $AUTHOR
#' @date $DATE

#' Clear session, just in case
rm(list=ls())

#' Create a data directory if none exists
dir.create("../output/")
dir.create("../output/figs/")

#' Source the functions and the dataset
source("functions/functions.R")
ds <- read.table("../data/${PROJECT}_data.csv.gz", 
	header=TRUE, na="", sep=",")
names(ds)

#' Load relevant libraries
library(ggplot2)
library(grid)
library(plyr)
library(reshape2)

#' Makes a simple plot theme, rather than use the default generated by
#' ggplot2
theme_set(theme_bw())

#' Generate plots

#' Clear session, just in case
rm(list=ls())
