##' The file contains code to analyze the data $DATA for the project
##' $PROJECT.  This script likely contains a large portion of code for
##' generating graphics, plots, and regression diagnostics.  However,
##' it may also contain code for the main analysis for the project.
##'
##' @author $AUTHOR
##' @date $DATE

##' Clear session, just in case
rm(list=ls())

##' Create a data directory if none exists
dir.create("../output/")
dir.create("../output/figs/")

##' Load in the dataset
ds <- read.table("../data/${PROJECT}_data.csv.gz", 
	header=TRUE, na="", sep=",")
names(ds)

##' Source personal functions, or install (or update) custom functions
##' in a package (to install from github, needs devtools)
##source("functions/functions.R")
library(devtools)
install_github("$GITHUBUSER/$GITHUBRPKG")
library($GITHUBRPKG)

##' Load relevant libraries
library(ggplot2)
library(grid)
library(plyr)
library(reshape2)

##' Makes a simple plot theme, rather than use the default generated by
##' ggplot2
theme_set(theme_bw())
##themeWhite()

##' Generate plots

##' Clear session, just in case
rm(list=ls())
